DarthVanger/NeuralNotes

.babelrc, package.json, server/server.js
Make ability to build react app.
=> Add live reload and ES6 support for server.

server/server.js
Disable built-in hot reload for webpack server;
Disable host checking;
=> Deploy fixes

src/api/google-api-loader.js, src/components/NotesMindMapView/NotesMindMapViewActions.js, src/components/NotesMindMapView/NotesMindMapViewComponent.js, src/components/NotesMindMapView/NotesMindMapViewContainer.js, src/components/NotesMindMapView/NotesMindMapViewSagas.js, src/helpers/visNetwork.js
removed google api multiple initialization;
removed unnecessary comments;
=> WIP: refactor NotesMindMapView component;

.eslintrc.js, package.json, webpack.config.js
Reduces bundle size. @DarthVanger This will not break the build, I have commented the analyzer method in the webpack config to avoid build errors.
=> Reduce the bundle size

src/components/LoginPage/LoginPageComponent.js, src/components/LoginPage/Slide1.js, src/components/LoginPage/Slide2.js, src/components/LoginPage/Slide3.js, src/components/LoginPage/Slide5.js, src/components/LoginPage/slideComponents.js
Fix style bugs on the login page:
- Increase font-size for headings
- Make images bigger on slides 1,2,3,5
- Fix a typo on a button:  "Sing up..." -> "Sign up..."
fix #73
=> Issue #73. Design bugs on login page

package.json, src/components/NoteNameEditor/NoteNameEditorComponent.js, src/components/NotesContentEditor/NotesContentEditorComponent.js, src/components/SearchPanel/SearchPanelComponent.js, src/helpers/debounce.js, src/storage/noteStorageAPI.js
Removes lodash & underscore dependencies.
fixes #57
=> Removes lodash & underscore

src/components/NotesMindMap/NotesMindMapComponent.js, src/components/NotesMindMap/NotesMindMapContainer.js, src/components/NotesMindMap/NotesMindMapReducer.js, src/helpers/graph.js
Code clean up after #70 
fixes #75
=> Code clean-up after #70

src/components/LoginPage/LoginPageComponent.js
- Duplicate GoogleSignUp button styled-component
- Move out common styles into Button styled-component
- Reuse Button styled-component in GoogleSignUp and GoogleLoginButton
Implement #61
=> Add login button on the top of the landing page

src/components/TopBar/TopBarStyles.js
=> Fix the gap caused by TopBar's styles

src/components/NotesPage/NotesPageComponent.js, src/components/TopBar/TopBarStyles.js
- TopBarComponent move upper in order;
- Add z-index for StyledHeader in order to correct view of shadows and gradient line;
Minor changes
=> Change component order in NotesPageComponent

src/components/NotesPage/NotesPageComponent.js, src/components/OpenFileButton/OpenFileButtonComponent.js, src/components/OpenFileButton/OpenFileButtonStyles.js
- Create OpenFileButtonComponent without functionality;
- Implement design for OpenFileButtonComponent;
Resolve #117
=> Open file: implement design of 'Open in G-Drive' button

src/colors.js, src/components/NoteDetails/NoteDetailsStyles.js
=> Update NoteDetails styles

src/api/google-drive-api.js, src/components/NotesMindMap/NotesMindMapActions.js, src/components/NotesMindMap/NotesMindMapReducer.js, src/components/NotesMindMap/NotesMindMapSagas.js, src/components/SearchPage/SearchPageComponent.js, src/components/TopBar/TopBarComponent.js
- Changed the search by folders instead of files.
- Redraw the mind map, showing that note and its children.
=> Issue #12 Finish Search notes functionality

package.json
Closes https://github.com/DarthVanger/NeuralNotes/issues/65
=> delete: winston from deps

src/index.html
There has been a wrong configured link to google fonts, this PR fixes it
#175
=> Fixed roboto font

package.json
The problem occurs in v1.0.7, see https://github.com/crubier/react-graph-vis/issues/111
=> Fix react-graph-vis error

src/components/NotesPage/NotesPageTopBar.js
and fix styles of buttons.
Maybe I need to move the code from NotesPageTopBar to TopBar components?
=> Added burger-menu, moved the logout button to the menu

package.json, src/components/LogoutButton/LogoutButtonComponent.js, src/components/NotesPage/NotesPageTopBar.js
The component <ToolBar> (inside <NotesPageTopBar>) has inline styles with media queries, so there can be 3 component heights: 48px, 56px and 64px, depending on the window width and device orientation.
=> Correct design NotesPageTopBar and LogoutButton.

src/components/NoteDetails/NoteDetailsComponent.js, src/components/NoteDetails/NoteDetailsPage.js, src/components/NoteDetails/NoteDetailsStyles.js
Now background displayed as in Figma.
=> Fixed colors and styles NoteDetails

src/components/LoginPage/LoginPageComponent.js, src/globalStyles.js, src/theme.js
Also deleted font-family from theme and components.
=> Fixed font in globalStyle

src/components/SearchPage/SearchInput.js, src/components/SearchPage/SearchPageComponent.js
Add style top search bar component on NoteSearch page
=> Implement top search bar
